server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/ecommercedb?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Initializer script configurations
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# Email Configurations
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=aura.55697648@gmail.com
spring.mail.password=YOUR_GMAIL_APP_PASSWORD_HERE
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
